version: "3.3"

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx.docker
    ports:
      - 8080:443
      - 80:80
    links:
      - php-fpm
    volumes:
      - ./:/var/www
      - ./docker/nginx/ssl:/etc/nginx/ssl
  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm.docker
    volumes:
      - ./:/var/www
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal. remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    links:
      - mysql
      - redis
  php-cli:
    build:
      context: .
      dockerfile: docker/php-cli.docker
    volumes:
      - ./:/var/www
    links:
      - mysql
      - redis
    tty: true
  mysql:
    image: mysql:5.7
    volumes:
      - ./storage/docker/mysql:/var/lib/mysql
    ports:
      - 33061:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravelblog
  redis:
    image: redis:3.0
    ports:
      - 63791:6379
  node:
    build:
      context: .
      dockerfile: docker/node.docker
    volumes:
      - ./:/var/www
    tty: true
